name: SmpCore
version: '{{ version }}'
main: wtf.gacek.smpcore.SmpCore
api-version: 1.19
authors: [ GacekKosmatek ]
permissions:
  smpcore.reload:
    default: op
  smpcore.pvpenable:
      default: true

commands:
  smpcore:
    usage: "/smpcore"
    description: "Main SMP Core command"
    permission: smpcore.reload
  pvp:
    usage: "/pvp enable"
    description: "Disables your pvp protection"
    permission: smpcore.pvpenable